### PR TITLE
Typo: “suplied” should be “supplied”

### PR DESCRIPTION
**Pull request by andylolz**
screen shot 2018-12-04 at 10 13 27

### CODE REVIEW

**Comment by andylolz** [comment]
Replaces OpenDataServices/cove#1093.

**Comment by ghost** [comment]
Thank you for finding this repo and adding this! We'll add a quick entry to the /CHANGELOG.md file following the https://keepachangelog.com/en/1.0.0/ format, so something like 

    ### Fixed

    - Typo in "This is because all data **suplied** to this website is automatically deleted "

I know it seems pedantic but I'm trying to get us in the habit of doing this in all our libs - now we have many developers it helps keep track and keep up to speed on what has changed. 

Also, in this case, I assume we have an associated translation for this and we'll have to make sure that  is copied across and pulled back - so if that's grand I'll assign this to @rhiaro who can do this (maybe teaching me at the same time for the future).

**Comment by andylolz** [comment]
> I'm trying to get us in the habit of doing this in all our libs

Good plan! I’ve added an entry based on your suggestion.

**Review by rhiaro — APPROVED** [review]

**Comment by andylolz** [comment]
:tada:

**Pull request merged**
