### PR TITLE
fix: Handle an invalid URL from the submission form

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Review by Bjwebb — CHANGES_REQUESTED** [review]
This looks good, could you add a CHANGELOG entry?

**Comment by jpmckinney** [comment]
Done!

**Review by Bjwebb — APPROVED** [review]

**Comment by Bjwebb** [comment]
This is now in the latest PyPI release: https://pypi.org/project/libcoveweb/0.30.3/

Looks like there's some trouble in the CI, related to the latest version of openpyxl. I think use openpyxl 3.1.2 or earlier for now.

**Comment by jpmckinney** [comment]
Hi @Bjwebb , it seems like the exception needs to be `requests.exceptions.InvalidURL` not `requests.InvalidURL`.

**Pull request merged**
