### PR TITLE
Include all files in package uploaded to PyPi

### PR DESCRIPTION
**Pull request by ghost**
#38

### CODE REVIEW

**Comment by ghost** [comment]
[Set up Hotjar](https://trello.com/c/KLHW48Fc/18-set-up-hotjar)

**Comment by Bjwebb** [comment]
Is it possible to make an automated test of this?

**Comment by ghost** [comment]
@Bjwebb Possibly, but what would you be testing against? Is it safe to assume that everything in the "cove" directory should be in the package?

**Comment by ghost** [comment]
If so, would it work just sticking in:
```

    package_data={
        'cove': [
            '*',
            '*/*',
            '*/*/*',
            '*/*/*/*',
            '*/*/*/*/*',
            '*/*/*/*/*/*',
            '*/*/*/*/*/*/*',
                    ]
    },
```

**Comment by Bjwebb** [comment]
Is it possible to create the package, and then use it instead of the code dir to run the unit tests?

**Comment by ghost** [comment]
Note: if you pass ** and setuptools passes recursive=True it works https://docs.python.org/3/library/glob.html#glob.glob

**Comment by ghost** [comment]
Talked to ben

Test: If we do all the stars, will it include all the python compiled files?

If so, leave as it
If not, change to all the stars.

Tests on Travis: Noted that a lot of the files that might go missing aren't covered in tests, but tests are still good - try and use packaged on Travis. 

Maybe delete cove older and copy one from package back into place before running tests? 

Or can we create fresh virtualenv and install into that?

Run tests twice - once directly, then on package - then it's immediately clear where any problems are

**Comment by ghost** [comment]
Can we use build matrix and run two at once?

**Comment by ghost** [comment]
> Test: If we do all the stars, will it include all the python compiled files?

Yes it will.

But to double check, I tested it with the code as in this pull request (special paths only). It still included the _ _ pycache _ _ files!

**Comment by ghost** [comment]
[Make sure all our packages on PyPi are packaged properly](https://trello.com/c/Z9si9gmZ/37-make-sure-all-our-packages-on-pypi-are-packaged-properly)

**Comment by Bjwebb** [comment]
BTW, [for lib-cove-bods](https://github.com/openownership/lib-cove-bods/blob/ceed7a57140b7600d19316a32445cc2b451e5706/setup.py#L26) we use `include_package_data=True`, which is [an alternative to  package_data](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files). Looks like it can even include files based on what's in source control. (In fact it seems to be happening for lib-cove-bods, as the files keep being included even when I delete the MANIFEST file.)

**Comment by Bjwebb** [comment]
@odscjames What do you think of my change in https://github.com/OpenDataServices/lib-cove-web/pull/39/commits/29c76b853c717171163e0a1b2792a43f2ac8e327?

I've tested it, and it seems to include the files we want. With this change, I'm much happier to see this merged.

**Comment by ghost** [comment]
I'm sure I tried that and had some issue. But if you've tested it and it worked then sure.

**Comment by Bjwebb** [comment]
Not sure what testing I did before, looks like we're missing `requirements.in`, at least.

**Comment by Bjwebb** [comment]
> But to double check, I tested it with the code as in this pull request (special paths only). It still included the _ _ pycache _ _ files!

Looks like this is to do with caching. I ran into the same problem, but `rm -r dist libcoveweb.egg-info; python setup.py sdist` fixes it.

**Comment by Bjwebb** [comment]
@odscjames Yes you're right, `include_package_data=True` doesn't seem to include templates, so I think we should go with what you had originally.

I've rebased your work, and added a commit to move requirements into setup.py (as requirements.in was not included, but this is the direction we want to go anyway). Could you check taht this looks okay? (I can't assign you as reviewer because you made the original PR).

**Comment by ghost** [comment]
I approve this P.R. up to commit 4ee7259ed1c1f4cc0e4edd98a294c5eea8221297 but I can't approve cos i created it! @Bjwebb

**Review by Bjwebb — APPROVED** [review]

**Comment by jpmckinney** [comment]
FYI, in my experience, creating/updating a MANIFEST.in with check-manifest is more reliable than managing this in setup.py: https://ocp-software-handbook.readthedocs.io/en/latest/python/packages.html#release-process

**Pull request merged**
