### PR TITLE
Put Link input first

### LINKED ISSUE #1201: OCDS: Put "Link" option first and expanded
Users submit data via a link many times more frequently than by upload or paste: https://standard.open-contracting.org/review/stats/

### PR DESCRIPTION
**Pull request by rhiaro**
Fixes https://github.com/OpenDataServices/cove/issues/1201 but also affects other coves. I think that's okay, but want to confirm.

### CODE REVIEW

**Comment by rhiaro** [comment]
[Put "Link" option first and expanded](https://trello.com/c/kGCrk6ut/21-put-link-option-first-and-expanded)

**Comment by robredpath** [comment]
@rhiaro would this affect all other CoVEs, or just 360 + IATI?

**Comment by rhiaro** [comment]
All of them. They depend on lib-cove-web and none of them override input.html

**Comment by robredpath** [comment]
@rhiaro pretty sure we've discussed this elsewhere, but confirming here - this definitely shouldn't be applied to 360 CoVE, and it would be preferable for it not to be applied to IATI CoVE. I've not checked on BODS CoVE.

**Comment by rhiaro** [comment]
Closing, superseded by https://github.com/OpenDataServices/lib-cove-web/pull/34 (which allows it to be applied on a per-CoVE basis)

**Pull request closed without merging**
