### PR TITLE
Refactor input template

### PR DESCRIPTION
**Pull request by rhiaro**
This makes it so the input.html template can be overridden by individual CoVEs via the `COVE_CONFIG`. It's so we can do https://github.com/OpenDataServices/cove/issues/1201 just for OCDS without affecting the others.

### CODE REVIEW

**Comment by rhiaro** [comment]
[Put "Link" option first and expanded](https://trello.com/c/kGCrk6ut/21-put-link-option-first-and-expanded)

**Comment by rhiaro** [comment]
[Put "Link" option first and expanded](https://trello.com/c/kGCrk6ut/21-put-link-option-first-and-expanded)

**Review by ghost — DISMISSED** [review]

**Review by Bjwebb — CHANGES_REQUESTED** [review]
This is a Changed, so should be a new MINOR release.

**Comment by rhiaro** [comment]
Fixed, cheers @Bjwebb

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
