### PR TITLE
Apply styling changes for 360 cove metadata support

### PR DESCRIPTION
**Pull request by robredpath**

### CODE REVIEW

**Comment by robredpath** [comment]
Copied from https://github.com/OpenDataServices/cove/pull/1193

**Comment by ghost** [comment]
Assuming you've checked and these aren't used on other coves? If so sure.

But it needs a changelog entry.

**Comment by robredpath** [comment]
@odscjames I'm assuming so. 

I've updated the README to mention the changelog, and updated the changelog with what I assume is going to be the version number

**Comment by ghost** [comment]
See https://github.com/OpenDataServices/lib-cove-web/pull/26#issuecomment-508170439 - I think there is some confusion about the use of the unreleased heading.

**Comment by kindly** [comment]
@robredpath  I think the css should be added here:
https://github.com/OpenDataServices/cove/blob/master/cove_360/sass/_custom-360.scss

(remembering to run `build_360.sh` in the same directory after.)

I think this styling is 360 specific and should not be added here.  It was also save the need to do a new release!

**Comment by robredpath** [comment]
@kindly ah, ok - I just took the patch from your original work and applied it to the same file in its new location; I didn't think we'd refactored 360's styling as part of the lib work. 

I'll update to move the styling to a more appropriate place - thanks!

**Pull request closed without merging**
