### PR TITLE
cove 360 new design changes

### PR DESCRIPTION
**Pull request by BibianaC**
- Delete 360 logo. It is saved in cove and cove-opendataservices-coop repositories.
- Delete lib-cove-web/cove/templates/multi_index.html. Not being used (it was replaced by the static site at cove-opendataservices-coop).

cove: https://github.com/OpenDataServices/cove/pull/1282
cove-opendataservices-coop: https://github.com/OpenDataServices/cove-opendataservices-coop/pull/2

Both pull requests need to be deployed before merging this one.

### CODE REVIEW

**Comment by BibianaC** [comment]
[Cove rebrand - Replace logo](https://trello.com/c/qC79uAnp/67-cove-rebrand-replace-logo)

**Review by michaelwood — CHANGES_REQUESTED** [review]
The new logo in this pull request has different dimensions to the original one so either it needs to be made square or the HTML needs updating in cove (not sure why this is here and the template is is in cove!) https://github.com/OpenDataServices/cove/blob/master/cove_360/templates/cove_360/base.html#L11

**Comment by BibianaC** [comment]
@odscjames what would you think if we move the 360 logo to cove 360?

**Comment by ghost** [comment]
Yes, ideally the image file would be in the cove repository and not here, as it's not relevant to other clients. This would be a nice bit of tidying up to do if possible.

But https://github.com/OpenDataServices/lib-cove-web/blob/74d4d46e1b618432826685483bc370ca2044fc83/cove/templates/multi_index.html#L12 seems to reference the image too - what does that template do?

Maybe for this bit of work we can add the new image file into the cove repository with a different name and edit https://github.com/OpenDataServices/cove/blob/master/cove_360/templates/cove_360/base.html#L11 and any other uses of it in the Cove repository?

And make an issue asking the above question so we hopefully get to that and tidy that up later.

**Comment by Bjwebb** [comment]
> But `lib-cove-web/cove/templates/multi_index.html` seems to reference the image too - what does that template do?

That template was used to generate the page at http://cove.opendataservices.coop/. Its now been replaced with a static site. The template can probably be removed.

I guess http://cove.opendataservices.coop/ is another place we might want to change the logo. The git repo for that is https://github.com/OpenDataServices/cove-opendataservices-coop

**Comment by BibianaC** [comment]
Thanks for your help!
@michaelwood @odscjames @Bjwebb I have changed the approach based on your comments. Please see new PR description.

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
