### PR TITLE
Update 360's address

### PR DESCRIPTION
**Pull request by robredpath**

### CODE REVIEW

**Comment by ghost** [comment]
This pull request in itself looks fine, but the other pull request also has the same version number in!

Normally we do changelog entries under the "## [Unreleased]" heading, and only put in a new version number when we know we are going to release as soon as we merge it to master - otherwise the version numbers in the changelog might stop matching the actual tagged and released versions.

Here's an example: https://github.com/openownership/lib-cove-bods/blob/master/CHANGELOG.md


If there are several changes to make to this repo to release in one go, it would be better to do pull requests under the "## [Unreleased]" heading, and then when everything is in master, do a pull request that does the release only

(Also, just remembered, if we are adding a version number for a new release, the number in setup.py needs to change too!)

**Comment by robredpath** [comment]
Thanks @odscjames - that's not documented in the developer docs, so I was confused as to what the 'Unreleased' heading was, when what followed it was clearly a list of things that had been released. 

I'm intending to get release out straight away. Although, I've also changed my mind and think this should be a PATCH bump, not a MINOR.

I've given up on the other PR against this repo for now and gotten a dev version of the relevant code live for people to test using just the commit. I'll update the PR to not try to release straight away and it can wait until we're ready

**Comment by robredpath** [comment]
Ah, I can see it's on the KeepAChangelog site. I've added https://github.com/OpenDataServices/developer-docs/pull/75 to make it so that I would have read that!

**Comment by robredpath** [comment]
@odscjames @kindly what do we need to do in order to get this merged?

**Review by ghost — APPROVED** [review]

**Pull request merged**
