### PR TITLE
python: Drop Python 3.6 support & actions: Fix bug

### PR DESCRIPTION
**Pull request by ghost**
Python 3.6 is not supported & some of our dependencies don't support it

pip resolver feature not available any more and not needed

### CODE REVIEW

**Review by Bjwebb — APPROVED** [review]
As noted on IRC, openownership still use 3.6, but we're hoping to migrate that soon. Happy that they'll be pinned to an older version in the meantime.

**Review by jpmckinney — COMMENTED** [review]
Hmm, code doesn’t use any Python 3.7-only features. It’s just that you can’t test on 3.6 anymore due to CI platform changes. I’d leave out the change to setup.py

**Comment by ghost** [comment]
I'd like the changes to setup.py to be in as it communicates to people and limits pip. Essentially, we are saying we don't care about this running on Python 3.6 anymore and if someone did introduce some 3.7+ only code tomorrow that would be fine. Putting it in setting.py: 
* is clear communication of the intended support for this code in a place more people will look than Github Actions
* limits pip; if someone running 3.6 tries to pip install it it won't install versions later than the current one (0.25.0) and thus the person will get a older version that we (in theory!) know works on 3.6.


ps. You can actually test in CI on 3.6 by specifying an older version of Ubuntu, but in this case there was other dependency issues so it seemed to me to be a simpler and better solution to just drop 3.6 support. As far as I know, no-one needs 3.6 support for this - I am assuming OCDS doesn't?

**Comment by jpmckinney** [comment]
OCP has some services running on 3.6, but they will be upgraded to 3.8 or 3.10.

You can communicate officially supported versions with `classifiers` like `Programming Language :: Python :: 3.7`, etc. That is the best place for clear communication of the intended support.

With `python_requires`, if a user is stuck on 3.6 but wants to use a new version, they can't – even if the new version actually works in 3.6. The truth is this code does not require 3.7+.

At present, no other package published by ODSC has python_requires >= 3, even though most of the code will not work in Python 2. I think that's reasonable, since users should not expect packages to work on end-of-life versions.

I've had issues on other packages where a maintainer pre-emptively added the restriction even though it wasn't necessary, and this meant I had to fork to track upstream improvements.

**Comment by ghost** [comment]
So the problem I had with Python 3.6 is that attrs is going to drop support for it soon. So in this case, at some point soon this library will stop working on 3.6 without more packaging work by us or users. Given that, in this specific case I'm happy adding python_requires.

Generally I think I lean towards using python_requires. 

* ODSC has a very unaggressive deprecation policy - Python 3.6 officially left support a year ago! In my experience, most Python packages use end of official support as the point that they drop support too, so we are behind most other people. This means we should cause a minimum of problems.
* Using a package in a Python version that the maintainer doesn't want to support any more is a power user situation and I think not the usual case. I'm happy using python_requires with the idea that this will give safety for most users, and for power users a bit more friction (forking the repository) is ok.
* We do actually use it elsewhere  - in any case we never had a policy to **not** use it in the past, so a lack of it on a repository shouldn't be taken to signify too much.
* On classifiers, somehow I had picked up the impression they weren't current practice but now I google them it looks like I was wrong. I'm happy to look at them again for all our libraries. But I still think enforcing safety is good.

I'm happy to continue discussing the general point (and any other packaging issues) in a suitable discussion forum though.

But in this specific case, I've chatted to folk here and I'm going to merge this now.

**Comment by jpmckinney** [comment]
Fair enough. Though this library will continue to work even once attrs drops support, because pip will just resolve to an older version of attrs. There's only a problem if you start requiring a recent version of attrs. That said, when I search this repo for attrs, I don't get any results. jsonschema requires attrs, but it allows `>=17.4.0` from 2017...

For my part, I only set `python_requires` when the code *actually requires* newer versions of Python, i.e. it uses a new feature of the language. (And even then, I only bother to set it if my package fails on non-end-of-life versions. I figure anyone running end-of-life versions doesn't expect any guarantees about new versions continuing to work. But, I agree that in such cases it'd be more responsible to set a minimum version *when in fact required*.)

**Pull request merged**
