### PR TITLE
[OpenDataServices/cove#1106] Display an error's line number

### PR DESCRIPTION
**Pull request by Bjwebb**
(IATI only for the foreseeable future)

### CODE REVIEW

**Comment by ghost** [comment]
Should the text in templates be in tags so it can be I18N'd? Apart from that looks good.

**Comment by Bjwebb** [comment]
Quite possibly! There's "Sheet" and "Row" that also aren't translated.

**Comment by ghost** [comment]
I would say that fixing already problematic code is a different issue, but we should try and avoid adding more problematic code tho. (If this is problematic, @rhiaro is our I18N expert?)

**Comment by rhiaro** [comment]
Yeah when I finish moving strings out of `lib-cove` to `lib-cove-web` I will do a full audit and make sure all strings are translatable, but when adding new strings please do wrap them in `{% trans "translate me" %}` (templates) or `_('translate me')` (in code).

**Comment by ghost** [comment]
The code looks fine to me but I'm not sure if anything should be done with the Transifex files - it should be possible for me to work that out from the docs given more time, I will try to do that soon (or does @rhiaro want to review?)

**Comment by Bjwebb** [comment]
The new strings appear only on IATI CoVE, which we don't translate atm, so we may be able to get away without pushing this particular PR to Transifex.

**Review by rhiaro — APPROVED** [review]
I updated the .po file to add the new strings, but didn't push to transifex yet since we don't need those translations urgently. They'll get pushed next time we do any string updates.

**Pull request merged**
